LauraPerson/search-4-class

app/models/user.rb, config/routes.rb, db/migrate/20200502174650_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
=> create user model

app/models/course.rb, db/migrate/20200502183911_create_courses.rb, db/schema.rb, test/models/course_test.rb
=> did courses model

app/models/booking.rb, db/migrate/20200502190101_create_bookings.rb, db/schema.rb, test/models/booking_test.rb
=> Created booking model

app/models/course.rb, app/models/user.rb, db/migrate/20200502192519_add_first_name_to_user.rb, db/migrate/20200502192543_add_last_name_to_user.rb, db/schema.rb
=> Added first name, last name, and references

app/controllers/bookings_controller.rb, app/controllers/courses_controller.rb, app/controllers/users_controller.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb, test/controllers/courses_controller_test.rb, test/controllers/users_controller_test.rb
=> Add Routes and Controllers

app/controllers/courses_controller.rb, app/views/courses/index.html.erb, app/views/courses/show.html.erb, app/views/users/edit.html.erb, app/views/users/show.html.erb
Created views structure... ready to go!
=> Created views structure

app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
=> added names

app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/controllers/courses_controller.rb, app/controllers/pages_controller.rb, app/controllers/users_controller.rb, app/models/category.rb, app/models/course.rb, app/models/user.rb, app/views/courses/_form.html.erb, app/views/courses/index.html.erb, app/views/courses/show.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20200506003903_create_categories.rb, db/migrate/20200506010320_add_category_to_courses.rb, db/migrate/20200506014955_remove_category_from_courses.rb, db/schema.rb, db/seeds.rb, test/models/category_test.rb
Create some validations for the Course Model and create the category model.
Validations : Presence for all attributes of the course + Can't add a date which is in past + can't create null or negative price and duration
Ps : I had to delete the first category attributes we created for the Course because it was no longer useful, now we'll pass by the Category Model :)
=> Start with validations & category model

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/controllers/courses_controller.rb, app/controllers/users_controller.rb, app/policies/application_policy.rb, app/policies/booking_policy.rb, app/policies/course_policy.rb, app/policies/user_policy.rb, test/policies/booking_policy_test.rb, test/policies/course_policy_test.rb, test/policies/user_policy_test.rb
Installed and Created pundit  --> done!
=> Installed and Created pundit

app/views/courses/_form.html.erb
=> Correct the form style

app/controllers/bookings_controller.rb, app/policies/booking_policy.rb, app/views/courses/show.html.erb, app/views/users/show.html.erb
Add the booking reservation in the App
=> Add the booking reservation

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card.scss, app/controllers/courses_controller.rb, app/models/course.rb, app/views/courses/index.html.erb, app/views/pages/home.html.erb
Not front home but index page front end 
- did cards with teacher and course infomation
=> did card index page

app/assets/stylesheets/components/_button.scss, app/views/users/show.html.erb
Corrected first last name interpolation and card
=> Corrected first last name interpolation and card

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_button.scss, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
Navbar buttons and logo added.
=> Navbar style done

app/assets/stylesheets/components/_card.scss, app/views/users/show.html.erb
Booking cards display corrected. Working
=> Booking cards display corrected

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_home.scss, app/views/courses/_form.html.erb, app/views/courses/index.html.erb, app/views/courses/show.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
=> Correct some front design

app/models/course.rb, app/views/pages/home.html.erb
=> Correct search

app/assets/stylesheets/components/_alert.scss, app/controllers/courses_controller.rb, app/views/courses/show.html.erb
Delete the booking buttons when the user already booked the course
=> User can't book a class twice

app/controllers/users_controller.rb, app/views/courses/show.html.erb, app/views/users/show.html.erb
Add the possibility to click on the profile picture of the teacher to see his pages with his classes
Did some front in user#showpage, replaced 'courses' by 'class'
=> Did teacher profile link in show#courses and some front in user#show

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
Added footer with social icons. email contact and copyright
=> Footer done

app/assets/stylesheets/components/_footer.scss, app/views/shared/_footer.html.erb
Fiz algumas alterações no footer que eu nao tinha visto no codigo (principalmente pra tirar o text-decoration das icones). Se ta ok pra vocês podem dar o merge.
=> Delete text-decoration + reduce copyrigth

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/config/_colors.scss, app/views/courses/index.html.erb
Added map aside courses list when had presential courses, map fixed when scrolling
=> Added map aside courses list when had presential courses
